// ============================================================================
// MEDIDAS - RECURSOS HUMANOS E PRODUTIVIDADE
// ============================================================================
// Modelo: Star Schema
// Tabelas: FactAtendimentosUrgencia, FactCustos, DimProfissionais
// Cobertura RH: 92.1% dos registos (4.271 de 4.636 linhas)
// ============================================================================


// ============================================================================
// 1. CONTAGENS BÁSICAS DE PROFISSIONAIS
// ============================================================================

Total Profissionais = 
    [Total Médicos] + [Total Médicos Internos] + [Total Enfermeiros]

Total Médicos = 
    SUM(FactAtendimentosUrgencia[Médicos])

Total Médicos Internos = 
    SUM(FactAtendimentosUrgencia[MedicosInternos])

Total Enfermeiros = 
    SUM(FactAtendimentosUrgencia[Enfermeiros])

Total Médicos Completo = 
    [Total Médicos] + [Total Médicos Internos]

Total Técnicos = 
    CALCULATE(
        SUM(DimProfissionais[NºProfissionais]),
        DimIdPorf[Profissao] IN {"Tec. Sup. Saúde", "Tec. Sup. Diag. terapêutica"}
    )


// ============================================================================
// 2. RÁCIOS DE PROFISSIONAIS
// ============================================================================

Rácio Enfermeiro/Médico = 
    DIVIDE([Total Enfermeiros], [Total Médicos], 0)

Rácio Enfermeiro/Médico Completo = 
    DIVIDE([Total Enfermeiros], [Total Médicos Completo], 0)

Rácio Médicos por 1000 Atendimentos = 
    VAR _Medicos = [Total Médicos]
    VAR _Atendimentos = [Total Atendimentos]
    RETURN
        DIVIDE(_Medicos * 1000, _Atendimentos, 0)

Rácio Enfermeiros por 1000 Atendimentos = 
    VAR _Enfermeiros = [Total Enfermeiros]
    VAR _Atendimentos = [Total Atendimentos]
    RETURN
        DIVIDE(_Enfermeiros * 1000, _Atendimentos, 0)


// ============================================================================
// 3. PRODUTIVIDADE (Atendimentos por Profissional)
// ============================================================================

Atendimentos por Médico = 
    DIVIDE([Total Atendimentos], [Total Médicos], 0)

Atendimentos por Enfermeiro = 
    DIVIDE([Total Atendimentos], [Total Enfermeiros], 0)

Atendimentos por Profissional = 
    DIVIDE([Total Atendimentos], [Total Profissionais], 0)

Atendimentos por Médico Completo = 
    DIVIDE([Total Atendimentos], [Total Médicos Completo], 0)


// ============================================================================
// 4. COMPARAÇÃO COM MÉDIA NACIONAL
// ============================================================================

Rácio Enfermeiro/Médico - Média Nacional = 
    VAR _RacioAtual = [Rácio Enfermeiro/Médico]
    VAR _MediaNacional = 
        CALCULATE(
            [Rácio Enfermeiro/Médico],
            ALL(DimInstituicao),
            ALL(DimRegiao)
        )
    RETURN
        _RacioAtual - _MediaNacional

Atendimentos por Profissional - Média Nacional = 
    VAR _AtendAtual = [Atendimentos por Profissional]
    VAR _MediaNacional = 
        CALCULATE(
            [Atendimentos por Profissional],
            ALL(DimInstituicao),
            ALL(DimRegiao)
        )
    RETURN
        _AtendAtual - _MediaNacional

Produtividade vs Nacional (%) = 
    VAR _Atual = [Atendimentos por Profissional]
    VAR _Nacional = 
        CALCULATE(
            [Atendimentos por Profissional],
            ALL(DimInstituicao),
            ALL(DimRegiao)
        )
    RETURN
        DIVIDE(_Atual - _Nacional, _Nacional, 0)


// ============================================================================
// 5. ANÁLISE DE CUSTOS POR PROFISSIONAL
// ============================================================================

Custo por Profissional = 
    VAR _CustoTotal = SUM(FactCustos[Despesa])
    VAR _NumProfissionais = [Total Profissionais]
    RETURN
        DIVIDE(_CustoTotal, _NumProfissionais, BLANK())

Custo por Médico = 
    VAR _CustoTotal = SUM(FactCustos[Despesa])
    VAR _NumMedicos = [Total Médicos]
    RETURN
        DIVIDE(_CustoTotal, _NumMedicos, BLANK())

Custo por Enfermeiro = 
    VAR _CustoTotal = SUM(FactCustos[Despesa])
    VAR _NumEnfermeiros = [Total Enfermeiros]
    RETURN
        DIVIDE(_CustoTotal, _NumEnfermeiros, BLANK())

Custo por Profissional - Média Nacional = 
    VAR _CustoAtual = [Custo por Profissional]
    VAR _MediaNacional = 
        CALCULATE(
            [Custo por Profissional],
            ALL(DimInstituicao),
            ALL(DimRegiao)
        )
    RETURN
        _CustoAtual - _MediaNacional


// ============================================================================
// 6. INDICADORES DE EFICIÊNCIA
// ============================================================================

Score Eficiência RH = 
    VAR _AtendPorProf = [Atendimentos por Profissional]
    VAR _MediaAtendPorProf = 
        CALCULATE(
            [Atendimentos por Profissional],
            ALL(DimInstituicao)
        )
    VAR _RacioAtual = [Rácio Enfermeiro/Médico]
    VAR _RacioIdeal = 2.0
    VAR _ScoreProdutividade = DIVIDE(_AtendPorProf, _MediaAtendPorProf, 1) * 60
    VAR _ScoreRacio = MIN(DIVIDE(_RacioAtual, _RacioIdeal, 0), 1) * 40
    RETURN
        _ScoreProdutividade + _ScoreRacio

Score Produtividade = 
    VAR _Atual = [Atendimentos por Profissional]
    VAR _Media = 
        CALCULATE(
            [Atendimentos por Profissional],
            ALL(DimInstituicao)
        )
    RETURN
        DIVIDE(_Atual, _Media, 0) * 100


// ============================================================================
// 7. INDICADORES DE ALERTA
// ============================================================================

Status Rácio Enfermeiro/Médico = 
    VAR _Racio = [Rácio Enfermeiro/Médico]
    RETURN
        SWITCH(
            TRUE(),
            _Racio >= 2.0, "✅ ADEQUADO",
            _Racio >= 1.5, "⚠️ ATENÇÃO",
            _Racio >= 1.0, "🔶 DÉFICE",
            "🔴 CRÍTICO"
        )

Status Produtividade = 
    VAR _Score = [Score Produtividade]
    RETURN
        SWITCH(
            TRUE(),
            _Score >= 120, "⭐ EXCELENTE",
            _Score >= 100, "✅ ADEQUADA",
            _Score >= 80, "⚠️ ABAIXO MÉDIA",
            "🔴 CRÍTICA"
        )

Alerta RH = 
    VAR _Racio = [Rácio Enfermeiro/Médico]
    VAR _Produtividade = [Score Produtividade]
    RETURN
        SWITCH(
            TRUE(),
            _Racio < 1.5 && _Produtividade < 80, "🔴 DÉFICE CRÍTICO RH",
            _Racio < 1.5, "🔶 DÉFICE ENFERMEIROS",
            _Produtividade < 80, "⚠️ PRODUTIVIDADE BAIXA",
            "✅ Sem Alertas"
        )

⚠ Rácio Enfermeiro/Médico Abaixo de 2 = 
    IF([Rácio Enfermeiro/Médico] < 2, "⚠️ Rácio baixo", "✅ OK")

⚠ Produtividade Baixa = 
    VAR _AtendPorProf = [Atendimentos por Profissional]
    VAR _MediaNacional = 
        CALCULATE(
            [Atendimentos por Profissional],
            ALL(DimInstituicao)
        )
    RETURN
        IF(_AtendPorProf < _MediaNacional * 0.8, "⚠️ Produtividade < 80% média", "✅ OK")

⚠ Custo por Profissional Elevado = 
    VAR _CustoPorProf = [Custo por Profissional]
    VAR _MediaNacional = 
        CALCULATE(
            [Custo por Profissional],
            ALL(DimInstituicao)
        )
    RETURN
        IF(_CustoPorProf > _MediaNacional * 1.2, "⚠️ Custo > 120% média", "✅ OK")


// ============================================================================
// 8. EVOLUÇÃO TEMPORAL (Year over Year)
// ============================================================================

Total Profissionais Ano Anterior = 
    CALCULATE(
        [Total Profissionais],
        SAMEPERIODLASTYEAR(DimCalendar[Data])
    )

Variação YoY Profissionais = 
    [Total Profissionais] - [Total Profissionais Ano Anterior]

% Variação YoY Profissionais = 
    DIVIDE(
        [Variação YoY Profissionais],
        [Total Profissionais Ano Anterior],
        0
    )

Variação YoY Médicos = 
    VAR _Atual = [Total Médicos]
    VAR _Anterior = 
        CALCULATE(
            [Total Médicos],
            SAMEPERIODLASTYEAR(DimCalendar[Data])
        )
    RETURN
        DIVIDE(_Atual - _Anterior, _Anterior, 0)

Variação YoY Enfermeiros = 
    VAR _Atual = [Total Enfermeiros]
    VAR _Anterior = 
        CALCULATE(
            [Total Enfermeiros],
            SAMEPERIODLASTYEAR(DimCalendar[Data])
        )
    RETURN
        DIVIDE(_Atual - _Anterior, _Anterior, 0)

Variação % Custo por Profissional YoY = 
    VAR _AnoAtual = [Custo por Profissional]
    VAR _AnoAnterior = 
        CALCULATE(
            [Custo por Profissional],
            SAMEPERIODLASTYEAR(DimCalendar[Data])
        )
    RETURN
        DIVIDE(_AnoAtual - _AnoAnterior, _AnoAnterior, BLANK())


// ============================================================================
// 9. ANÁLISE DE COBERTURA DE DADOS
// ============================================================================

Tem Dados RH = 
    IF([Total Profissionais] > 0, "SIM", "NÃO")

% Registos com Dados RH = 
    VAR _TotalRegistos = COUNTROWS(FactAtendimentosUrgencia)
    VAR _RegistrosComRH = 
        CALCULATE(
            COUNTROWS(FactAtendimentosUrgencia),
            FactAtendimentosUrgencia[Médicos] > 0 || 
            FactAtendimentosUrgencia[Enfermeiros] > 0
        )
    RETURN
        DIVIDE(_RegistrosComRH, _TotalRegistos, 0)


// ============================================================================
// 10. CORRELAÇÕES E ANÁLISES CRUZADAS
// ============================================================================

Correlação RH vs Tempo Espera = 
    // Para usar em scatter plot: Atendimentos por Profissional (X) vs Tempo Espera (Y)
    // Correlação negativa esperada: mais profissionais = menos tempo espera
    "Use em Scatter Plot: X = Atend/Prof | Y = Tempo Espera"

Défice Enfermeiros Estimado = 
    VAR _EnfermeirosAtuais = [Total Enfermeiros]
    VAR _MedicosAtuais = [Total Médicos]
    VAR _EnfermeirosNecessarios = _MedicosAtuais * 2  // Rácio ideal = 2.0
    VAR _Deficit = _EnfermeirosNecessarios - _EnfermeirosAtuais
    RETURN
        IF(_Deficit > 0, _Deficit, 0)


// ============================================================================
// 11. RANKINGS E BENCHMARKING
// ============================================================================

Ranking Produtividade = 
    RANKX(
        ALL(DimInstituicao[InstituicaoNome]),
        [Atendimentos por Profissional],
        ,
        DESC,
        DENSE
    )

Ranking Rácio Enfermeiro/Médico = 
    RANKX(
        ALL(DimInstituicao[InstituicaoNome]),
        [Rácio Enfermeiro/Médico],
        ,
        DESC,
        DENSE
    )

Top 20% Produtividade = 
    IF(
        [Ranking Produtividade] <= COUNTROWS(ALL(DimInstituicao)) * 0.2,
        "SIM",
        "NÃO"
    )


// ============================================================================
// NOTAS DE UTILIZAÇÃO E DOCUMENTAÇÃO
// ============================================================================
//
// 📊 COBERTURA DE DADOS:
//    • Dados RH disponíveis: 92.1% dos registos (4.271 de 4.636 linhas)
//    • Use filtro [Tem Dados RH] = "SIM" para análises precisas
//    • 7.9% registos sem dados RH (365 linhas)
//
// 🏗️ ESTRUTURA DO MODELO:
//    • FactAtendimentosUrgencia: Médicos, MedicosInternos, Enfermeiros
//    • FactCustos: Despesa
//    • DimProfissionais: NºProfissionais, Profissao
//    • Relacionamentos: TimeKey, RegiaoID, InstituicaoID
//
// 🎯 RÁCIOS RECOMENDADOS:
//    • Rácio Enfermeiro/Médico: Meta >= 2.0
//      - Verde (✅): >= 2.0
//      - Amarelo (⚠️): 1.5-2.0
//      - Vermelho (🔴): < 1.5
//    • Score Produtividade: Comparar com média nacional
//      - Excelente (⭐): >= 120
//      - Adequada (✅): 100-120
//      - Abaixo (⚠️): 80-100
//      - Crítica (🔴): < 80
//
// 🔗 ANÁLISES CRUZADAS RECOMENDADAS:
//    1. RH + Atendimentos: Produtividade por tipo de urgência
//    2. RH + Custos: Eficiência financeira (filtrar [Tem Dados Custo])
//    3. RH + Tempo Espera: Correlação negativa esperada
//    4. RH + Qualidade: Impacto na satisfação do utente
//
// 📈 VISUALIZAÇÕES RECOMENDADAS:
//    1. Scatter Plot:
//       - X: Atendimentos por Profissional
//       - Y: Tempo Espera Médio
//       - Tamanho: Total Atendimentos
//       - Cor: Status Rácio Enfermeiro/Médico
//
//    2. Gauge Chart:
//       - Valor: Rácio Enfermeiro/Médico
//       - Zonas: Vermelho (0-1.5), Amarelo (1.5-2.0), Verde (>2.0)
//       - Target: 2.0
//
//    3. Line Chart:
//       - Séries: Médicos, Médicos Internos, Enfermeiros
//       - Eixo X: Data (mensal/trimestral)
//       - Mostrar variação YoY
//
//    4. Matrix:
//       - Linhas: Instituição
//       - Colunas: Rácios + Status + Alertas
//       - Valores: Códigos de cor condicionais
//
//    5. Bar Chart:
//       - Ranking Produtividade por Instituição
//       - Linha de referência: Média Nacional
//       - Destacar Top 20%
//
//    6. Card/KPI:
//       - Alertas críticos (🔴)
//       - Défice enfermeiros estimado
//       - % Variação YoY
//
// ⚠️ ALERTAS AUTOMÁTICOS:
//    • 🔴 Défice Crítico RH: Rácio < 1.5 AND Produtividade < 80%
//    • 🔶 Défice Enfermeiros: Rácio < 1.5
//    • ⚠️ Produtividade Baixa: Score < 80
//    • ⚠️ Custo Elevado: > 120% da média nacional
//
// 🚫 LIMITAÇÕES CONHECIDAS:
//    • Dados agregados mensalmente (não permite análise diária de turnos)
//    • Não distingue especialidades médicas
//    • Não inclui dados de ausências/férias/baixas
//    • Dados de custos podem ter granularidade diferente de RH
//
// 💡 BOAS PRÁTICAS:
//    1. Sempre filtrar por [Tem Dados RH] = "SIM" em análises detalhadas
//    2. Usar filtros temporais consistentes ao comparar custos vs RH
//    3. Agrupar por Região para análises de benchmarking
//    4. Combinar múltiplas medidas para análise holística
//    5. Validar outliers antes de tirar conclusões
//
// 🔄 MANUTENÇÃO:
//    • Atualizar [Rácio Ideal] se guidelines nacionais mudarem
//    • Rever limites de alertas anualmente
//    • Adicionar novas profissões em DimProfissionais conforme necessário
//
// ============================================================================